language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
    sudo: true
    dist: xenial
install:
- pip install --upgrade mypy
- pip install --upgrade .[qiskit,projectq] coveralls
env:
- API_URL=https://staging.quantum-inspire.com
script:
- echo "running unit tests"
- coverage run --source="./src/quantuminspire" -m unittest discover -s src/tests -t
  src -v
- echo "running mypy"
- MYPYPATH=./src mypy --strict --ignore-missing-imports -p quantuminspire
- echo "running examples"
- python ./docs/example_projectq_entangle.py
- python ./docs/example_projectq_grover.py
- python ./docs/example_qiskit_entangle.py
- echo "running notebooks"
- jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/example_projectq.ipynb
- jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/grover_algorithm_qi.ipynb
- jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/qi-performance-test.ipynb
after_success:
- coveralls
deploy:
  provider: pypi
  user: qinspire
  password:
    secure: Y4tj7rKrf+ExjlD6RNdAVYraTMelAVaSe9abhn4HFQLgvy5CqXGDcWl+df/MkHZVzYfjEe61Sb5dbxwEUd+7lmQBIKfJ0nC1a46qtQ2pqH/HnFm6bvyCRepfCWE01l7ZWnl3bcYK6gjaDST65NoxyTBTTQYsB48p16/zBh5CGxKq9fcsI3v2gBRxccyKk1a78tn4uWyQnGGDKIc6NW4TZpGAS6Kfj4CxWmiP5iiKBYm7O1nlvy66/lfpqNlFnw99ZVt/hvaKPzEFt1doZcit2Jdn/cjUoxKJLaq9IABsmOnXzW0VhNi9ro2GDciarUCL8xWyNXbqKxPWu4dyTeWzqk3WxkEJJeGh1pJUipyu+LSpDYseYFZVvY4VV/1ngjzCpbzR/2Bcf8m8bFOzB02u6UWbAv/+rqcwwMunzSi3Bze57gvx0pzPxwr2rGNYLpS+d4wbY9VRDeDAvd7VFFlEOFVDxE3t7mDr04YDaWMVaWBvHnmjYRfBHY70Vzr8R/yA63ODVjfvj5IsdlNrjSJRyAGrHAbabeXnuCCmcFXD6FkwzPtdl6Pd2r4NeBac8v+L3DiXwuD4Ll68pRUJ1O68ZwLIxwddPDYswTh/bixi4aaiDScH4qkvlieynyj/sf0tWBPhjSr568n7BqBL0TORIgWtvXwtXfiUiP1+QC1/7No=
  on:
    tags: true
    branch: master
  skip_existing: true
