language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      sudo: true
      dist: xenial
install:
  - pip install .[qiskit,projectq] coveralls
script:
  - coverage run --source="./src/quantuminspire" -m unittest discover -s src/tests -t src -v
after_success:
  - coveralls
