language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .[qiskit,projectq]
script:
  - coverage run python -m unittest discover -s src/tests -t src -v
after_success:
  - coverage report -m
